spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: YOUR GOOGLE APP CLIENTID ex: end with .apps.googleusercontent.com
            clientSecret: YOUR GOOGLE APP SECRET

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


  datasource:
    url: jdbc:mysql://localhost:3306/yohavo
    username: YOUR MYSQL USERNAME
    password: YOUR MYSQL PASSWORD

